TABLE_DESCRIPTIONS: dict[str, str] = {
    "departments": "部门信息表，记录企业或实验室内部的组织部门。",
    "users": "用户信息表，记录员工或实验室成员的基础信息及所属部门。",
    "projects": "项目表，记录科研、平台或业务项目的基本信息和状态。",
    "project_members": "项目成员关系表，记录用户参与项目的角色和加入时间。",
    "tasks": "任务表，记录项目任务、负责人、工时、优先级和完成状态。",
    "attendance_records": "考勤记录表，记录用户每日打卡、工时和出勤状态。",
    "devices": "设备表，记录实验设备、服务器或工作站等资源信息。",
    "device_usage_records": "设备使用记录表，记录用户在项目中使用设备的时间段和时长。",
    "meetings": "会议表，记录项目会议的时间、时长、主题和纪要。",
    "meeting_participants": "会议参与关系表，记录用户参加会议的情况。",
}


COLUMN_DESCRIPTIONS: dict[str, dict[str, str]] = {
    "departments": {
        "id": "部门 ID",
        "name": "部门名称",
        "description": "部门说明",
        "created_at": "创建时间",
    },
    "users": {
        "id": "用户 ID",
        "name": "用户姓名",
        "email": "用户邮箱",
        "department_id": "所属部门 ID",
        "role": "岗位或职责",
        "created_at": "创建时间",
    },
    "projects": {
        "id": "项目 ID",
        "name": "项目名称",
        "description": "项目说明",
        "status": "项目状态",
        "start_date": "项目开始日期",
        "end_date": "项目结束日期",
        "created_at": "创建时间",
    },
    "project_members": {
        "id": "项目成员关系 ID",
        "project_id": "项目 ID",
        "user_id": "用户 ID",
        "member_role": "用户在项目中的角色",
        "joined_at": "加入项目日期",
    },
    "tasks": {
        "id": "任务 ID",
        "project_id": "所属项目 ID",
        "assignee_id": "任务负责人用户 ID",
        "title": "任务标题",
        "status": "任务状态，例如 todo、in_progress、review、blocked、done；done 表示已完成，其他状态表示未完成",
        "priority": "任务优先级",
        "estimated_hours": "预计工时",
        "actual_hours": "实际工时",
        "due_date": "截止日期",
        "completed_at": "完成日期",
        "created_at": "创建时间",
    },
    "attendance_records": {
        "id": "考勤记录 ID",
        "user_id": "用户 ID",
        "work_date": "工作日期",
        "check_in_time": "签到时间",
        "check_out_time": "签退时间",
        "work_hours": "当天工作时长，单位小时",
        "status": "出勤状态，例如 normal、late、absent、overtime",
        "created_at": "创建时间",
    },
    "devices": {
        "id": "设备 ID",
        "name": "设备名称",
        "device_type": "设备类型",
        "location": "设备所在位置",
        "status": "设备状态",
        "created_at": "创建时间",
    },
    "device_usage_records": {
        "id": "设备使用记录 ID",
        "device_id": "设备 ID",
        "user_id": "使用设备的用户 ID",
        "project_id": "关联项目 ID",
        "start_time": "使用开始时间",
        "end_time": "使用结束时间",
        "duration_minutes": "使用时长，单位分钟",
        "created_at": "创建时间",
    },
    "meetings": {
        "id": "会议 ID",
        "project_id": "关联项目 ID",
        "title": "会议标题",
        "meeting_date": "会议时间",
        "duration_minutes": "会议时长，单位分钟",
        "summary": "会议纪要",
        "created_at": "创建时间",
    },
    "meeting_participants": {
        "id": "会议参与关系 ID",
        "meeting_id": "会议 ID",
        "user_id": "参会用户 ID",
        "created_at": "创建时间",
    },
}
